# This file was automatically created by FeynRules $Revision: 302 $
# Mathematica version: 7.0 for Mac OS X x86 (64-bit) (November 11, 2008)
# Date: Tue 31 Aug 2010 16:54:46


from __future__ import division
from object_library import all_particles, Particle

ve = Particle(pdg_code = 12,
              name = 've',
              antiname = 've~',
              spin = 2,
              color = 1,
              mass = 'ZERO',
              width = 'ZERO',
              texname = 've',
              antitexname = 've',
              line = 'straight',
              charge = 0,
              LeptonNumber = 1,
              GhostNumber = 0)

ve__tilde__ = ve.anti()

vm = Particle(pdg_code = 14,
              name = 'vm',
              antiname = 'vm~',
              spin = 2,
              color = 1,
              mass = 'ZERO',
              width = 'ZERO',
              texname = 'vm',
              antitexname = 'vm',
              line = 'straight',
              charge = 0,
              LeptonNumber = 1,
              GhostNumber = 0)

vm__tilde__ = vm.anti()

vt = Particle(pdg_code = 16,
              name = 'vt',
              antiname = 'vt~',
              spin = 2,
              color = 1,
              mass = 'ZERO',
              width = 'ZERO',
              texname = 'vt',
              antitexname = 'vt',
              line = 'straight',
              charge = 0,
              LeptonNumber = 1,
              GhostNumber = 0)

vt__tilde__ = vt.anti()

e__minus__ = Particle(pdg_code = 11,
                      name = 'e-',
                      antiname = 'e+',
                      spin = 2,
                      color = 1,
                      mass = 'ZERO',
                      width = 'ZERO',
                      texname = 'e-',
                      antitexname = 'e-',
                      line = 'straight',
                      charge = -1,
                      LeptonNumber = 1,
                      GhostNumber = 0)

e__plus__ = e__minus__.anti()

m__minus__ = Particle(pdg_code = 13,
                      name = 'm-',
                      antiname = 'm+',
                      spin = 2,
                      color = 1,
                      mass = 'ZERO',
                      width = 'ZERO',
                      texname = 'm-',
                      antitexname = 'm-',
                      line = 'straight',
                      charge = -1,
                      LeptonNumber = 1,
                      GhostNumber = 0)

m__plus__ = m__minus__.anti()

tt__minus__ = Particle(pdg_code = 15,
                       name = 'tt-',
                       antiname = 'tt+',
                       spin = 2,
                       color = 1,
                       mass = 'MTA',
                       width = 'ZERO',
                       texname = 'tt-',
                       antitexname = 'tt-',
                       line = 'straight',
                       charge = -1,
                       LeptonNumber = 1,
                       GhostNumber = 0)

tt__plus__ = tt__minus__.anti()

u = Particle(pdg_code = 2,
             name = 'u',
             antiname = 'u~',
             spin = 2,
             color = 3,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'u',
             antitexname = 'u',
             line = 'straight',
             charge = 2/3,
             LeptonNumber = 0,
             GhostNumber = 0)

u__tilde__ = u.anti()

c = Particle(pdg_code = 4,
             name = 'c',
             antiname = 'c~',
             spin = 2,
             color = 3,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'c',
             antitexname = 'c',
             line = 'straight',
             charge = 2/3,
             LeptonNumber = 0,
             GhostNumber = 0)

c__tilde__ = c.anti()

t = Particle(pdg_code = 6,
             name = 't',
             antiname = 't~',
             spin = 2,
             color = 3,
             mass = 'MT',
             width = 'WT',
             texname = 't',
             antitexname = 't',
             line = 'straight',
             charge = 2/3,
             LeptonNumber = 0,
             GhostNumber = 0)

t__tilde__ = t.anti()

d = Particle(pdg_code = 1,
             name = 'd',
             antiname = 'd~',
             spin = 2,
             color = 3,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'd',
             antitexname = 'd',
             line = 'straight',
             charge = -1/3,
             LeptonNumber = 0,
             GhostNumber = 0)

d__tilde__ = d.anti()

s = Particle(pdg_code = 3,
             name = 's',
             antiname = 's~',
             spin = 2,
             color = 3,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 's',
             antitexname = 's',
             line = 'straight',
             charge = -1/3,
             LeptonNumber = 0,
             GhostNumber = 0)

s__tilde__ = s.anti()

b = Particle(pdg_code = 5,
             name = 'b',
             antiname = 'b~',
             spin = 2,
             color = 3,
             mass = 'MB',
             width = 'ZERO',
             texname = 'b',
             antitexname = 'b',
             line = 'straight',
             charge = -1/3,
             LeptonNumber = 0,
             GhostNumber = 0)

b__tilde__ = b.anti()

ghA = Particle(pdg_code = 9000001,
               name = 'ghA',
               antiname = 'ghA~',
               spin = -1,
               color = 1,
               mass = 'ZERO',
               width = 'WghA',
               texname = 'ghA',
               antitexname = 'ghA',
               line = 'dotted',
               charge = 0,
               LeptonNumber = 0,
               GhostNumber = 1)

ghA__tilde__ = ghA.anti()

ghZ = Particle(pdg_code = 9000002,
               name = 'ghZ',
               antiname = 'ghZ~',
               spin = -1,
               color = 1,
               mass = 'MZ',
               width = 'WghZ',
               texname = 'ghZ',
               antitexname = 'ghZ',
               line = 'dotted',
               charge = 0,
               LeptonNumber = 0,
               GhostNumber = 1)

ghZ__tilde__ = ghZ.anti()

ghWp = Particle(pdg_code = 9000003,
                name = 'ghWp',
                antiname = 'ghWp~',
                spin = -1,
                color = 1,
                mass = 'MW',
                width = 'WghWp',
                texname = 'ghWp',
                antitexname = 'ghWp',
                line = 'dotted',
                charge = 1,
                LeptonNumber = 0,
                GhostNumber = 1)

ghWp__tilde__ = ghWp.anti()

ghWm = Particle(pdg_code = 9000004,
                name = 'ghWm',
                antiname = 'ghWm~',
                spin = -1,
                color = 1,
                mass = 'MW',
                width = 'WghWm',
                texname = 'ghWm',
                antitexname = 'ghWm',
                line = 'dotted',
                charge = -1,
                LeptonNumber = 0,
                GhostNumber = 1)

ghWm__tilde__ = ghWm.anti()

ghG = Particle(pdg_code = 9000005,
               name = 'ghG',
               antiname = 'ghG~',
               spin = -1,
               color = 8,
               mass = 'ZERO',
               width = 'WghG',
               texname = 'ghG',
               antitexname = 'ghG',
               line = 'dotted',
               charge = 0,
               LeptonNumber = 0,
               GhostNumber = 1)

ghG__tilde__ = ghG.anti()

A = Particle(pdg_code = 22,
             name = 'A',
             antiname = 'A',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'A',
             antitexname = 'A',
             line = 'wavy',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

Z = Particle(pdg_code = 23,
             name = 'Z',
             antiname = 'Z',
             spin = 3,
             color = 1,
             mass = 'MZ',
             width = 'WZ',
             texname = 'Z',
             antitexname = 'Z',
             line = 'wavy',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

W__plus__ = Particle(pdg_code = 24,
                     name = 'W+',
                     antiname = 'W-',
                     spin = 3,
                     color = 1,
                     mass = 'MW',
                     width = 'WW',
                     texname = 'W+',
                     antitexname = 'W+',
                     line = 'wavy',
                     charge = 1,
                     LeptonNumber = 0,
                     GhostNumber = 0)

W__minus__ = W__plus__.anti()

G = Particle(pdg_code = 21,
             name = 'G',
             antiname = 'G',
             spin = 3,
             color = 8,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'G',
             antitexname = 'G',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

H = Particle(pdg_code = 25,
             name = 'H',
             antiname = 'H',
             spin = 1,
             color = 1,
             mass = 'MH',
             width = 'WH',
             texname = '\\phi',
             antitexname = '\\phi',
             line = 'dashed',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

phi0 = Particle(pdg_code = 250,
                name = 'phi0',
                antiname = 'phi0',
                spin = 1,
                color = 1,
                mass = 'MZ',
                width = 'Wphi',
                texname = 'phi0',
                antitexname = 'phi0',
                line = 'dashed',
                GoldstoneBoson = True,
                charge = 0,
                LeptonNumber = 0,
                GhostNumber = 0)

phi__plus__ = Particle(pdg_code = 251,
                       name = 'phi+',
                       antiname = 'phi-',
                       spin = 1,
                       color = 1,
                       mass = 'MW',
                       width = 'Wphi2',
                       texname = '\\phi^+',
                       antitexname = '\\phi^+',
                       line = 'dashed',
                       GoldstoneBoson = True,
                       charge = 1,
                       LeptonNumber = 0,
                       GhostNumber = 0)

phi__minus__ = phi__plus__.anti()

#For gg>8g, uu~>8g and uu>uu6g

g13 = Particle(pdg_code = 9013,
             name = 'g13',
             antiname = 'g13',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g13',
             antitexname = 'g13',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g14 = Particle(pdg_code = 9014,
             name = 'g14',
             antiname = 'g14',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g14',
             antitexname = 'g14',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g15 = Particle(pdg_code = 9015,
             name = 'g15',
             antiname = 'g15',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g15',
             antitexname = 'g15',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g16 = Particle(pdg_code = 9016,
             name = 'g16',
             antiname = 'g16',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g16',
             antitexname = 'g16',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g17 = Particle(pdg_code = 9017,
             name = 'g17',
             antiname = 'g17',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g17',
             antitexname = 'g17',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g18 = Particle(pdg_code = 9018,
             name = 'g18',
             antiname = 'g18',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g18',
             antitexname = 'g18',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g19 = Particle(pdg_code = 9019,
             name = 'g19',
             antiname = 'g19',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g19',
             antitexname = 'g19',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g1a = Particle(pdg_code = 90110,
             name = 'g1a',
             antiname = 'g1a',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g1a',
             antitexname = 'g1a',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g21 = Particle(pdg_code = 9021,
             name = 'g21',
             antiname = 'g21',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g21',
             antitexname = 'g21',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g24 = Particle(pdg_code = 9024,
             name = 'g24',
             antiname = 'g24',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g24',
             antitexname = 'g24',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g25 = Particle(pdg_code = 9025,
             name = 'g25',
             antiname = 'g25',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g25',
             antitexname = 'g25',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g26 = Particle(pdg_code = 9026,
             name = 'g26',
             antiname = 'g26',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g26',
             antitexname = 'g26',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g27 = Particle(pdg_code = 9027,
             name = 'g27',
             antiname = 'g27',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g27',
             antitexname = 'g27',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g28 = Particle(pdg_code = 9028,
             name = 'g28',
             antiname = 'g28',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g28',
             antitexname = 'g28',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g29 = Particle(pdg_code = 9029,
             name = 'g29',
             antiname = 'g29',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g29',
             antitexname = 'g29',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g2a = Particle(pdg_code = 90210,
             name = 'g2a',
             antiname = 'g2a',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g2a',
             antitexname = 'g2a',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g31 = Particle(pdg_code = 9031,
             name = 'g31',
             antiname = 'g31',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g31',
             antitexname = 'g31',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g32 = Particle(pdg_code = 9032,
             name = 'g32',
             antiname = 'g32',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g32',
             antitexname = 'g32',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g35 = Particle(pdg_code = 9035,
             name = 'g35',
             antiname = 'g35',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g35',
             antitexname = 'g35',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g36 = Particle(pdg_code = 9036,
             name = 'g36',
             antiname = 'g36',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g36',
             antitexname = 'g36',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g37 = Particle(pdg_code = 9037,
             name = 'g37',
             antiname = 'g37',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g37',
             antitexname = 'g37',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g38 = Particle(pdg_code = 9038,
             name = 'g38',
             antiname = 'g38',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g38',
             antitexname = 'g38',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g39 = Particle(pdg_code = 9039,
             name = 'g39',
             antiname = 'g39',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g39',
             antitexname = 'g39',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g3a = Particle(pdg_code = 90310,
             name = 'g3a',
             antiname = 'g3a',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g3a',
             antitexname = 'g3a',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g41 = Particle(pdg_code = 9041,
             name = 'g41',
             antiname = 'g41',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g41',
             antitexname = 'g41',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g42 = Particle(pdg_code = 9042,
             name = 'g42',
             antiname = 'g42',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g42',
             antitexname = 'g42',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g43 = Particle(pdg_code = 9043,
             name = 'g43',
             antiname = 'g43',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g43',
             antitexname = 'g43',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g46 = Particle(pdg_code = 9046,
             name = 'g46',
             antiname = 'g46',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g46',
             antitexname = 'g46',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g47 = Particle(pdg_code = 9047,
             name = 'g47',
             antiname = 'g47',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g47',
             antitexname = 'g47',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g48 = Particle(pdg_code = 9048,
             name = 'g48',
             antiname = 'g48',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g48',
             antitexname = 'g48',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g49 = Particle(pdg_code = 9049,
             name = 'g49',
             antiname = 'g49',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g49',
             antitexname = 'g49',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g4a = Particle(pdg_code = 90410,
             name = 'g4a',
             antiname = 'g4a',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g4a',
             antitexname = 'g4a',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g51 = Particle(pdg_code = 9051,
             name = 'g51',
             antiname = 'g51',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g51',
             antitexname = 'g51',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g52 = Particle(pdg_code = 9052,
             name = 'g52',
             antiname = 'g52',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g52',
             antitexname = 'g52',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g53 = Particle(pdg_code = 9053,
             name = 'g53',
             antiname = 'g53',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g53',
             antitexname = 'g53',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g54 = Particle(pdg_code = 9054,
             name = 'g54',
             antiname = 'g54',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g54',
             antitexname = 'g54',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g57 = Particle(pdg_code = 9057,
             name = 'g57',
             antiname = 'g57',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g57',
             antitexname = 'g57',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g58 = Particle(pdg_code = 9058,
             name = 'g58',
             antiname = 'g58',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g58',
             antitexname = 'g58',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g59 = Particle(pdg_code = 9059,
             name = 'g59',
             antiname = 'g59',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g59',
             antitexname = 'g59',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g5a = Particle(pdg_code = 90510,
             name = 'g5a',
             antiname = 'g5a',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g5a',
             antitexname = 'g5a',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g61 = Particle(pdg_code = 9061,
             name = 'g61',
             antiname = 'g61',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g61',
             antitexname = 'g61',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g62 = Particle(pdg_code = 9062,
             name = 'g62',
             antiname = 'g62',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g62',
             antitexname = 'g62',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g63 = Particle(pdg_code = 9063,
             name = 'g63',
             antiname = 'g63',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g63',
             antitexname = 'g63',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g64 = Particle(pdg_code = 9064,
             name = 'g64',
             antiname = 'g64',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g64',
             antitexname = 'g64',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g65 = Particle(pdg_code = 9065,
             name = 'g65',
             antiname = 'g65',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g65',
             antitexname = 'g65',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g68 = Particle(pdg_code = 9068,
             name = 'g68',
             antiname = 'g68',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g68',
             antitexname = 'g68',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g69 = Particle(pdg_code = 9069,
             name = 'g69',
             antiname = 'g69',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g69',
             antitexname = 'g69',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g6a = Particle(pdg_code = 90610,
             name = 'g6a',
             antiname = 'g6a',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g6a',
             antitexname = 'g6a',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g71 = Particle(pdg_code = 9071,
             name = 'g71',
             antiname = 'g71',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g71',
             antitexname = 'g71',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g72 = Particle(pdg_code = 9072,
             name = 'g72',
             antiname = 'g72',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g72',
             antitexname = 'g72',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g73 = Particle(pdg_code = 9073,
             name = 'g73',
             antiname = 'g73',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g73',
             antitexname = 'g73',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g74 = Particle(pdg_code = 9074,
             name = 'g74',
             antiname = 'g74',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g74',
             antitexname = 'g74',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g75 = Particle(pdg_code = 9075,
             name = 'g75',
             antiname = 'g75',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g75',
             antitexname = 'g75',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g76 = Particle(pdg_code = 9076,
             name = 'g76',
             antiname = 'g76',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g76',
             antitexname = 'g76',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g79 = Particle(pdg_code = 9079,
             name = 'g79',
             antiname = 'g79',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g79',
             antitexname = 'g79',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g7a = Particle(pdg_code = 90710,
             name = 'g7a',
             antiname = 'g7a',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g7a',
             antitexname = 'g7a',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g81 = Particle(pdg_code = 9081,
             name = 'g81',
             antiname = 'g81',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g81',
             antitexname = 'g81',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g82 = Particle(pdg_code = 9082,
             name = 'g82',
             antiname = 'g82',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g82',
             antitexname = 'g82',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g83 = Particle(pdg_code = 9083,
             name = 'g83',
             antiname = 'g83',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g83',
             antitexname = 'g83',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g84 = Particle(pdg_code = 9084,
             name = 'g84',
             antiname = 'g84',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g84',
             antitexname = 'g84',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g85 = Particle(pdg_code = 9085,
             name = 'g85',
             antiname = 'g85',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g85',
             antitexname = 'g85',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g86 = Particle(pdg_code = 9086,
             name = 'g86',
             antiname = 'g86',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g86',
             antitexname = 'g86',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g87 = Particle(pdg_code = 9087,
             name = 'g87',
             antiname = 'g87',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g87',
             antitexname = 'g87',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g8a = Particle(pdg_code = 90810,
             name = 'g8a',
             antiname = 'g8a',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g8a',
             antitexname = 'g8a',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g91 = Particle(pdg_code = 9091,
             name = 'g91',
             antiname = 'g91',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g91',
             antitexname = 'g91',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g92 = Particle(pdg_code = 9092,
             name = 'g92',
             antiname = 'g92',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g92',
             antitexname = 'g92',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g93 = Particle(pdg_code = 9093,
             name = 'g93',
             antiname = 'g93',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g93',
             antitexname = 'g93',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g94 = Particle(pdg_code = 9094,
             name = 'g94',
             antiname = 'g94',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g94',
             antitexname = 'g94',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g95 = Particle(pdg_code = 9095,
             name = 'g95',
             antiname = 'g95',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g95',
             antitexname = 'g95',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g96 = Particle(pdg_code = 9096,
             name = 'g96',
             antiname = 'g96',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g96',
             antitexname = 'g96',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g97 = Particle(pdg_code = 9097,
             name = 'g97',
             antiname = 'g97',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g97',
             antitexname = 'g97',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g98 = Particle(pdg_code = 9098,
             name = 'g98',
             antiname = 'g98',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g98',
             antitexname = 'g98',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

ga2 = Particle(pdg_code = 9102,
             name = 'ga2',
             antiname = 'ga2',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'ga2',
             antitexname = 'ga2',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

ga3 = Particle(pdg_code = 9103,
             name = 'ga3',
             antiname = 'ga3',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'ga3',
             antitexname = 'ga3',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

ga4 = Particle(pdg_code = 9104,
             name = 'ga4',
             antiname = 'ga4',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'ga4',
             antitexname = 'ga4',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

ga5 = Particle(pdg_code = 9105,
             name = 'ga5',
             antiname = 'ga5',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'ga5',
             antitexname = 'ga5',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

ga6 = Particle(pdg_code = 9106,
             name = 'ga6',
             antiname = 'ga6',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'ga6',
             antitexname = 'ga6',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

ga7 = Particle(pdg_code = 9107,
             name = 'ga7',
             antiname = 'ga7',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'ga7',
             antitexname = 'ga7',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

ga8 = Particle(pdg_code = 9108,
             name = 'ga8',
             antiname = 'ga8',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'ga8',
             antitexname = 'ga8',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

ga9 = Particle(pdg_code = 9109,
             name = 'ga9',
             antiname = 'ga9',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'ga9',
             antitexname = 'ga9',
             line = 'curly',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

g0 = Particle(pdg_code = 9000,
             name = 'g0',
             antiname = 'g0',
             spin = 3,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'g0',
             antitexname = 'g0',
             line = 'wavy',
             charge = 0,
             LeptonNumber = 0,
             GhostNumber = 0)

u1 = Particle(pdg_code = 9001,
             name = 'u1',
             antiname = 'u1~',
             spin = 2,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'u1',
             antitexname = 'u1',
             line = 'straight',
             charge = 2/3,
             LeptonNumber = 0,
             GhostNumber = 0)

u1__tilde__ = u1.anti()

u2 = Particle(pdg_code = 9002,
             name = 'u2',
             antiname = 'u2~',
             spin = 2,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'u2',
             antitexname = 'u2',
             line = 'straight',
             charge = 2/3,
             LeptonNumber = 0,
             GhostNumber = 0)

u2__tilde__ = u2.anti()

u3 = Particle(pdg_code = 9003,
             name = 'u3',
             antiname = 'u3~',
             spin = 2,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'u3',
             antitexname = 'u3',
             line = 'straight',
             charge = 2/3,
             LeptonNumber = 0,
             GhostNumber = 0)

u3__tilde__ = u3.anti()

u4 = Particle(pdg_code = 9004,
             name = 'u4',
             antiname = 'u4~',
             spin = 2,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'u4',
             antitexname = 'u4',
             line = 'straight',
             charge = 2/3,
             LeptonNumber = 0,
             GhostNumber = 0)

u4__tilde__ = u4.anti()

u5 = Particle(pdg_code = 9005,
             name = 'u5',
             antiname = 'u5~',
             spin = 2,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'u5',
             antitexname = 'u5',
             line = 'straight',
             charge = 2/3,
             LeptonNumber = 0,
             GhostNumber = 0)

u5__tilde__ = u5.anti()

u6 = Particle(pdg_code = 9006,
             name = 'u6',
             antiname = 'u6~',
             spin = 2,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'u6',
             antitexname = 'u6',
             line = 'straight',
             charge = 2/3,
             LeptonNumber = 0,
             GhostNumber = 0)

u6__tilde__ = u6.anti()

u7 = Particle(pdg_code = 9007,
             name = 'u7',
             antiname = 'u7~',
             spin = 2,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'u7',
             antitexname = 'u7',
             line = 'straight',
             charge = 2/3,
             LeptonNumber = 0,
             GhostNumber = 0)

u7__tilde__ = u7.anti()

u8 = Particle(pdg_code = 9008,
             name = 'u8',
             antiname = 'u8~',
             spin = 2,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'u8',
             antitexname = 'u8',
             line = 'straight',
             charge = 2/3,
             LeptonNumber = 0,
             GhostNumber = 0)

u8__tilde__ = u8.anti()

u9 = Particle(pdg_code = 9009,
             name = 'u9',
             antiname = 'u9~',
             spin = 2,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'u9',
             antitexname = 'u9',
             line = 'straight',
             charge = 2/3,
             LeptonNumber = 0,
             GhostNumber = 0)

u9__tilde__ = u9.anti()

ua = Particle(pdg_code = 90010,
             name = 'ua',
             antiname = 'ua~',
             spin = 2,
             color = 1,
             mass = 'ZERO',
             width = 'ZERO',
             texname = 'ua',
             antitexname = 'ua',
             line = 'straight',
             charge = 2/3,
             LeptonNumber = 0,
             GhostNumber = 0)

ua__tilde__ = ua.anti()






